import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header, Footer} from "@/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className ="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className = "min-h-screen flex flex-col w-full dark:bg-black bg-white  dark:bg-dot-white/[0.4] bg-dot-black/[0.2]">
          <div className = "px-4 sm:px-6 md:px-8 lg:px-24 xl:px-44"><Header></Header></div>
            <main className="flex-grow px-4 sm:px-6 md:px-8 lg:px-24 xl:px-44 min-h-[150vh] py-10">{children}</main>
          <div className = "px-4 sm:px-6 md:px-8 lg:px-24 xl:px-44 border-t border-gray-200"><Footer></Footer></div>
        </div>
      </body>
    </html>
  );
}
